import{i as b,S as w,a as E}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const a={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later!",exception:"Exception: We have some issue with connection. Please try again later!"},i={blue:"#abd4f8",orange:"#f28111",red:"#e97782"},m={click:"click",submit:"submit"};function s(e,t){b.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}const g=document.querySelector(".gallery"),$=new w(".gallery a",{captionsData:"alt",captionDelay:250});function M(e){if(q(),!e.hits||e.hits.length===0){g.insertAdjacentHTML("beforeend",'<p class="no-results">No images found. Try another keyword!</p>');return}g.insertAdjacentHTML("beforeend",x(e)),$.refresh()}function x(e){return e.hits.map(({webformatURL:t,largeImageURL:r,tags:l,likes:o,views:n,comments:u,downloads:v})=>`
      <li class="gallery-item hvr-grow">
        <a class="gallery-link" href="${r}">
          <figure class="gallery-figure">
            <img class="gallery-image" src="${t}" alt="${l}" loading="lazy">
            <figcaption class="gallery-figcaption">
              <ul class="img-content-wrapper">
                <li>Likes<span>${o}</span></li>
                <li>Views<span>${n}</span></li>
                <li>Comments<span>${u}</span></li>
                <li>Downloads<span>${v}</span></li>
              </ul>
            </figcaption>
          </figure>
        </a>
      </li>`).join("")}function O(){document.querySelector(".loader-wrapper")||g.insertAdjacentHTML("beforeend",`<div class="loader-wrapper">
          <span class="loader"></span>
       </div>`)}function q(){const e=document.querySelector(".loader-wrapper");e&&e.remove()}const T="52967670-3351bf06a7f07a2e608e7cced",A="https://pixabay.com/api/",P={key:T,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function H(e,t=1){try{O();const r={...P,q:e,page:t},l=await E.get(A,{params:r});return l.data.totalHits===0&&s(a.noResults,i.yellow),l.data}catch(r){return G(r),null}}function G(e){if(e.response){const{data:t,status:r}=e.response;s(`${a.exception} (Status ${r}) ERROR: ${t}`,i.orange)}else e.request?s(`${a.exception} No response received from server.`,i.orange):s(`${a.exception} ${e.message}`,i.orange)}let f="",c=1,h="";const L=15,_=document.querySelector(".form"),d=document.querySelector(".gallery"),p=document.querySelector(".load-more-btn"),y=document.querySelector(".loader-wrapper");_.addEventListener("submit",N);p.addEventListener("click",C);async function C(){try{if(h=m.click,await S(f,c),c>1){const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,left:0,behavior:"smooth"})}}}catch(e){s(a.exception+e,i.orange)}}async function N(e){try{e.preventDefault();const t=e.target,r=t.elements.search.value.trim();if(h=m.submit,p.classList.remove("visible"),b.destroy(),f!==r&&(d.innerHTML="",f=r,c=1),!r){s(a.info,i.blue),d.innerHTML="";return}await S(f,c),t.reset()}catch(t){s(a.exception+t,i.orange)}}function R(){y&&(y.style.display="flex")}function k(){y&&(y.style.display="none")}async function S(e,t){R();try{e===f&&h===m.click&&(c+=1,t=c);const r=await H(e,t);if(I(r)){const l=r.totalHits-(t-1)*L;M(r),B(l)}}catch(r){s(a.exception+r,i.orange)}finally{k()}}function I(e){if(e){if(e.totalHits===0)return s(a.warning,i.red),d.innerHTML="",!1}else return d.innerHTML="",!1;return!0}function B(e){e<=L?(p.classList.remove("visible"),s(a.endOfSearch,i.blue)):p.classList.add("visible")}
//# sourceMappingURL=commonHelpers.js.map
