import{i as h,S as L,a as w}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const a={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later!",exception:"Exception: We have some issue with connection. Please try again later!"},s={blue:"#abd4f8",orange:"#f28111",red:"#e97782"},d={click:"click",submit:"submit"};function i(e,t){h.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}const m=document.querySelector(".gallery"),$=new L(".gallery a",{captionsData:"alt",captionDelay:250});function E(e){if(q(),!e.hits||e.hits.length===0){m.insertAdjacentHTML("beforeend",'<p class="no-results">No images found. Try another keyword!</p>');return}m.insertAdjacentHTML("beforeend",M(e)),$.refresh()}function M(e){return e.hits.map(({webformatURL:t,largeImageURL:r,tags:c,likes:o,views:n,comments:l,downloads:S})=>`
      <li class="gallery-item hvr-grow">
        <a class="gallery-link" href="${r}">
          <figure class="gallery-figure">
            <img class="gallery-image" src="${t}" alt="${c}" loading="lazy">
            <figcaption class="gallery-figcaption">
              <ul class="img-content-wrapper">
                <li>Likes<span>${o}</span></li>
                <li>Views<span>${n}</span></li>
                <li>Comments<span>${l}</span></li>
                <li>Downloads<span>${S}</span></li>
              </ul>
            </figcaption>
          </figure>
        </a>
      </li>`).join("")}function O(){document.querySelector(".loader-wrapper")||m.insertAdjacentHTML("beforeend",`<div class="loader-wrapper">
          <span class="loader"></span>
       </div>`)}function q(){const e=document.querySelector(".loader-wrapper");e&&e.remove()}const x="52967670-3351bf06a7f07a2e608e7cced",T="https://pixabay.com/api/",A={key:x,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function P(e,t=1){try{O();const r={...A,q:e,page:t},c=await w.get(T,{params:r});return c.data.totalHits===0&&i(a.noResults,s.yellow),c.data}catch(r){return H(r),null}}function H(e){if(e.response){const{data:t,status:r}=e.response;i(`${a.exception} (Status ${r}) ERROR: ${t}`,s.orange)}else e.request?i(`${a.exception} No response received from server.`,s.orange):i(`${a.exception} ${e.message}`,s.orange)}let u="",f=1,p="";const b=15,G=document.querySelector(".form"),g=document.querySelector(".gallery"),y=document.querySelector(".load-more-btn");G.addEventListener("submit",_);y.addEventListener("click",async()=>{try{p=d.click,await v(u,f);const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,left:0,behavior:"smooth"})}}catch(e){i(a.exception+e,s.orange)}});async function _(e){try{e.preventDefault();const t=e.target,r=t.elements.search.value.trim();if(p=d.submit,y.classList.remove("visible"),h.destroy(),(u!==r||p===d.submit)&&(g.innerHTML="",u=r,f=1),!r){i(a.info,s.blue),g.innerHTML="";return}await v(u,f),t.reset()}catch(t){i(a.exception+t,s.orange)}}async function v(e,t){try{e===u&&p===d.click&&(f+=1,t=f);const r=await P(e,t);if(N(),R(r)){const c=r.totalHits-(t-1)*b;E(r),C(c)}}catch(r){i(a.exception+r,s.orange)}}function N(){const e=document.querySelector(".loader-wrapper");e&&e.remove()}function R(e){return e?e.totalHits===0?(i(a.warning,s.red),g.innerHTML="",!1):!0:(g.innerHTML="",!1)}function C(e){e<=b?(y.classList.remove("visible"),i(a.endOfSearch,s.blue)):y.classList.add("visible")}
//# sourceMappingURL=commonHelpers.js.map
