import{i as h,S,a as L}from"./assets/vendor-BgmC94F3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const s={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later!",exception:"Exception: We have some issue with connection. Please try again later!"},a={blue:"#abd4f8",orange:"#f28111",red:"#e97782"},f={click:"click",submit:"submit"};function i(e,t){h.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}const y=document.querySelector(".gallery"),w=new S(".gallery a",{captionsData:"alt",captionDelay:250});function E(e){if(O(),!e.hits||e.hits.length===0){y.insertAdjacentHTML("beforeend",'<p class="no-results">No images found. Try another keyword!</p>');return}y.insertAdjacentHTML("beforeend",$(e)),w.refresh()}function $(e){return e.hits.map(({webformatURL:t,largeImageURL:r,tags:c,likes:o,views:n,comments:l,downloads:b})=>`
      <li class="gallery-item hvr-grow">
        <a class="gallery-link" href="${r}">
          <figure class="gallery-figure">
            <img class="gallery-image" src="${t}" alt="${c}" loading="lazy">
            <figcaption class="gallery-figcaption">
              <ul class="img-content-wrapper">
                <li>Likes<span>${o}</span></li>
                <li>Views<span>${n}</span></li>
                <li>Comments<span>${l}</span></li>
                <li>Downloads<span>${b}</span></li>
              </ul>
            </figcaption>
          </figure>
        </a>
      </li>`).join("")}function M(){y.insertAdjacentHTML("beforeend",`<div class='loader-wrapper'>
        <div class='loader'></div>
    </div>`)}function O(){const e=document.querySelector(".loader-wrapper");e&&e.remove()}const x="52967670-3351bf06a7f07a2e608e7cced",T="https://pixabay.com/api/",q={key:x,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function A(e,t=1){try{M();const r={...q,q:e,page:t},c=await L.get(T,{params:r});return c.data.totalHits===0&&i(s.noResults,a.yellow),c.data}catch(r){P(r)}}function P(e){if(e.response){const{data:t,status:r}=e.response;i(`${s.exception} (Status ${r}) ERROR: ${t}`,a.orange)}else e.request?i(`${s.exception} No response received from server.`,a.orange):i(`${s.exception} ${e.message}`,a.orange)}let u="",d=1,p="";const H=15,G=document.querySelector(".search-form"),m=document.querySelector(".gallery"),g=document.querySelector(".load-more-btn");G.addEventListener("submit",_);g.addEventListener("click",async()=>{try{p=f.click,await v(u,d);const e=document.querySelector("li"),{height:t}=e.getBoundingClientRect();N(t*2,0)}catch(e){i(s.exception+e,a.orange)}});async function _(e){try{e.preventDefault();const t=e.target,r=t.elements.search.value.trim();if(p=f.submit,g.classList.remove("visible"),h.destroy(),(u!==r||p===f.submit)&&(m.innerHTML="",u=t.elements.search.value.trim(),d=1),!r){i(s.info,a.blue),m.innerHTML="";return}await v(u,d),t.reset()}catch(t){i(s.exception+t,a.orange)}}async function v(e,t){try{e===u&&p===f.click&&(d+=1,t+=1);const r=await A(e,t);if(R(),I(r)){const c=Math.round(r.totalHits/t);E(r),k(c)}}catch(r){i(s.exception+r,a.orange)}}function N(e=0,t=0){window.scrollBy({top:e,left:t,behavior:"smooth"})}function R(){document.querySelector(".loader-wrapper").remove()}function I(e){return e?e&&e.totalHits===0?(i(s.warning,a.red),m.innerHTML="",!1):!0:(m.innerHTML="",!1)}function k(e){if(e<=H){g.classList.remove("visible"),i(s.endOfSearch,a.blue);return}g.classList.add("visible")}
//# sourceMappingURL=commonHelpers.js.map
